export default {
  CALCULATOR_SCREEN: 'CALCULATOR',
  HOME_SCREEN: 'HOME',
  LOGIN_SCREEN: 'LOGIN',
  SERVICE_SCREEN: 'SERVICE',
  FUEL_LEDGER_SCREEN: 'FUEL_LEDGER',
  PROFILE_SCREEN: 'PROFILE',
  BOTTOM_TAB: 'BOTTOM_TAB',
};
