export default {
  CALCULATOR_SCREEN: 'CALCULATOR',
  HOME_SCREEN: 'HOME',
  LOGIN_SCREEN: 'LOGIN',
  SERVICE_SCREEN: 'SERVICE',
  FUEL_LEDGER_SCREEN: 'FUEL_LEDGER',
  PROFILE_SCREEN: 'PROFILE',
  BOTTOM_TAB: 'BOTTOM_TAB',
  FUEL_ENTRY_SCREEN: 'FUEL_ENTRY',
  ADD_VEHICLE_SCREEN: 'ADD_VEHICLE',
  ADD_SERVICE_SCREEN: 'ADD_SERVICE',
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE',
};
