export default {
  APP_NAME: 'Tern',
  APP_TAG_LINE: 'Simplify Your Drive, Empower Your Journey with Tern!',
  FUEL_PRICE: 'Fuel price',
  FUEL_EFFECIENCY: 'Fuel effeciency',
  DISTANCE: 'Distance',
  ADD_PEOPLE: 'Add people',
  CLEAR: 'Clear',
  CALCULATE: 'Calculate',
  ADD_DETAILS_TOAST: 'Please provide the necessary details to proceed with the calculation.',
  NUMBER_OF_PEOPLE: 'Number of people',
  ADD: 'Add',
  PER: 'per',
  EACH_SHARE: 'each share',
  PEOPLE: 'people',
  DISTANCE_UNIT: 'Distance Unit',
  FUEL_UNIT: 'Fuel Unit',
  CONTINUE_WITH_GOOGLE: 'Continue with Google',
  SKIP: 'Skip',
  HOME: 'Home',
  PROFILE: 'Profile',
  SERVICE: 'Service',
  LEDGER: 'Ledger',
};
